float64 distance            # in meters
int16 speed                 # in RPM
int16 speed_start           # speed to start with in RPM. if equal to 'speed', no acceleration is used
Direction direction         # DIRECTION_FORWARD(1) or DIRECTION_BACKWARD(2)
---
---
float64 remaining_distance  # in meters