float64 distance            # in meters
float32 speed               # in m/s
Direction direction         # DIRECTION_FORWARD(1) or DIRECTION_BACKWARD(2)
---
---
float64 remaining_distance  # in meters