raros:
  magnet:
    ros__parameters:
      active: true
      pin: 25

  buzzer:
    ros__parameters:
      active: true
      pin: 13

  color_sensor:
    ros__parameters:
      active: true
      gain: 16
      integration_time: 120

  range_sensor:
    ros__parameters:
      active: true
      pwm_pin_servo: 12
      sensor_front:
        trigger_pin: 23
        echo_pin: 24
      sensor_back:
        trigger_pin: 8
        echo_pin: 7

  camera:
    ros__parameters:
      active: true
      pwm_pin_servo_horizontal: 5
      pwm_pin_servo_vertical: 6

  collision_detection:
    ros__parameters:
      active: true
      threshold: 20