raros:
  magnet:
    ros__parameters:
      active: true
      pin: 25
  buzzer:
    ros__parameters:
      active: true
      pin: 13
  camera:
    ros__parameters:
      active: true
      pwm_pin_servo_horizontal: 5
      pwm_pin_servo_vertical: 6