@startuml nodes

frame "Raspberry Pi" as pi{
    node navigation
    node magnet
    node camera
    node color_sensor
    node ultrasonic_sensors
    node buzzer

    queue "motor_cmd"
    queue "motor_status"
    queue "color"
    queue "distance"
}

frame "Arduino" as arduino{
    node motor_control
}


color_sensor -down-> color
ultrasonic_sensors --> distance
distance -right-> navigation
navigation --> motor_cmd
motor_cmd -down-> motor_control
motor_control -> motor_status


@enduml