# service to interact with the Rotate action. See action_api node for more details.

float32 angle               # in degrees
Direction direction         # DIRECTION_LEFT(3) or DIRECTION_RIGHT(4)
---
unique_identifier_msgs/UUID goal_id    # The id of the requested goal