# service to interact with the Move action. See action_api node for more details.

float64 distance            # in meters
float32 speed               # in m/s
uint8 direction             # 1 (forward) or 2(backward)
---
unique_identifier_msgs/UUID goal_id    # The id of the requested goal