on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  RAROS_IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
  RAROS_API_IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}_api

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push raros_api
        uses: docker/build-push-action@v4
        with:
          context: apps/api
          file: apps/api/Dockerfile
          push: true
          tags: ${{ RAROS_API_IMAGE_NAME }}:latest, ${{ RAROS_API_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Build and push raros
        uses: docker/build-push-action@v4
        with:
          context: apps/ros2
          file: apps/ros2/Dockerfile
          push: true
          tags: ${{ RAROS_IMAGE_NAME }}:latest, ${{ RAROS_IMAGE_NAME }}:${{ github.ref_name }}