name: Create and publish docker images

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  RAROS_IMAGE_NAME: ghcr.io/francwhite/raros
  RAROS_API_IMAGE_NAME: ghcr.io/francwhite/raros_api

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push raros_api
        uses: docker/build-push-action@v4
        with:
          context: apps/api
          file: apps/api/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.RAROS_API_IMAGE_NAME }}:latest, ${{ env.RAROS_API_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Build and push raros
        uses: docker/build-push-action@v4
        with:
          context: apps/ros2
          file: apps/ros2/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.RAROS_IMAGE_NAME }}:latest, ${{ env.RAROS_IMAGE_NAME }}:${{ github.ref_name }}