name: Release

on:
  release:
    types: [published]

jobs:
  publish_client:
    uses: ./.github/workflows/publish_client.yaml
    secrets: inherit
  publish_images:
    uses: ./.github/workflows/docker.yaml